### ISSUE TITLE
[LAHI Support] Some help in fixing existing rules

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/LAHI#73]
## Support ticket 
https://avni.freshdesk.com/a/tickets/2603

## Tasks 
LAHI, needs help in debugging & fixing following rules-

- [x] LAHI ALUMNI PROFILE Encounter >> LAHI Alumni Status >> Rule not working
- [x] Respective cards not updating counts under offline dashboard
- [ ] ALUMNI CONNECT, contacted and not contacted this month offline cards not updating counts again.
- [x] One extra individual count appearing under Total Alumini dashboard card

Anybody picking this card can use user - dipali@lahi /password

**Comment by BEULAHEVANJALIN** [comment]
1. For the first point, I have added a validation error
2. Since some records have a null value in the alumni status, these were not updated on the card
3.  It's getting updated. 
4.  Seems to be working fine. Not able to find the issue. Moving to testing.
